### ISSUE TITLE
Need help.

### ISSUE THREAD

**Issue by sundog259** [darkerz7/EntWatchSharp#3]
In the maps ze_fapescape_p and ze_fapescape_rote_p, the map items use the func_physbox entity as trigger buttons, and it seems that the plugin cannot detect this type of trigger.
![1cf9438e0e7f2d024dc5611777675ea0](https://github.com/user-attachments/assets/1d1bcbaf-30f1-4da4-b308-139d88280ee6)

**Comment by sundog259** [comment]
entwatch config:https://github.com/UpKK-Xnet-YYDCS/UPKK_ZE_PUBLIC/blob/master/cs2/entwatch/maps/ze_fapescape_p.json

**Comment by darkerz7** [comment]
Fixed in version 0.DZ.2.alpha, thanks
