### ISSUE TITLE
Not an Issue, just an idea. Custom info from translate json

### ISSUE THREAD

**Issue by Andrey309a** [darkerz7/EntWatchSharp#7]
Can you add to the next stable version that is custom what is in the chat?

EntWatch] Fisherman used Electro Bow
Instead of:
[EntWatch] Fisherman[#8|STEAM_1:0:20461326] used Electro Bow

I think the steamid that was used in csgo in cs2 is no longer used and many of the plugins don't respond to the player id, so all that information is useless.

Ty!

**Comment by darkerz7** [comment]
With the correct use of api CS#, both userid and steamid are available and much more
https://github.com/roflmuffin/CounterStrikeSharp/blob/main/managed/CounterStrikeSharp.API/Modules/Commands/Targeting/Target.cs#L68

**Comment by Andrey309a** [comment]
Another thing that I have seen that does not work well are the bans, it seems that they are permanent regardless of the minutes you set.
![Captura de pantalla 2024-11-13 084640](https://github.com/user-attachments/assets/fc0b460d-c0f4-447f-be36-57b19a819066)

In !ebanlist still show the punishement but with !estatus no, said you have no active punishments

**Comment by darkerz7** [comment]
Due to the peculiarities of working with a database with asynchronous requests, the automatic unban time may differ by 3 minutes.

**Comment by Andrey309a** [comment]
I have checked it again and despite spending 10 minutes, the ban is not removed. 
The console is also giving this error:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CS2_CustomIO.CustomIO.KV_Speed(CEntityInstance cEntity, String[] keyvalue)
   at CS2_CustomIO.CustomIO.OnInput(DynamicHook hook)
   at InvokeStub_Func`2.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

**Comment by darkerz7** [comment]
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object. at CS2_CustomIO.CustomIO.KV_Speed(CEntityInstance cEntity, String[] keyvalue) at CS2_CustomIO.CustomIO.OnInput(DynamicHook hook) at InvokeStub_Func`2.Invoke(Object, Span`1) at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) --- End of inner exception stack trace --- at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at System.Delegate.DynamicInvokeImpl(Object[] args) at CounterStrikeSharp.API.Core.FunctionReference.b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

Map?

**Comment by Andrey309a** [comment]
I don't know the map, but it may have been my problem, I'll let you know if it keeps coming up.

**Comment by darkerz7** [comment]
> I have checked it again and despite spending 10 minutes, the ban is not removed. The console is also giving this error:
type of database?

**Comment by Andrey309a** [comment]
> > I have checked it again and despite spending 10 minutes, the ban is not removed. The console is also giving this error:
> 
> type of database?

mysql

**Comment by darkerz7** [comment]
No errors?

**Comment by Andrey309a** [comment]
> No errors?

No errors in entwatch folder.
Anyway do not worry, it may simply be that it was my fault of some ip blocking of the databases, if I get any error again I will provide it to you.

**Comment by darkerz7** [comment]
as far as I remember, when launching mysql deamon with default settings there are some problems

**Comment by darkerz7** [comment]
Default encoding and user permissions

**Comment by Andrey309a** [comment]
I'm already using it like this

**Comment by Andrey309a** [comment]
Is it possible to add the commands that have to be put in server.cfg in a cfg so that it does not appear that they are changed whenever the map is changed?

**Comment by darkerz7** [comment]
> Is it possible to add the commands that have to be put in server.cfg in a cfg so that it does not appear that they are changed whenever the map is changed?

https://github.com/darkerz7/EntWatchSharp?tab=readme-ov-file#cvars
