### ISSUE TITLE
Drop item still can use it

### ISSUE THREAD

**Issue by Andrey309a** [darkerz7/EntWatchSharp#8]
Here is a video where the problem is: https://medal.tv/es/games/counter-strike-2/clips/jgIY9cuKJliJUCsWD/wqY5KFMvh9UY?invite=cr-MSxBcVEsMjE5ODQzMTIyLA

![entwatch_slaybug](https://github.com/user-attachments/assets/95fb39ae-fd72-40b4-963a-6190bc6705d9)
Also an image where a slay is made and appears in chat all the items that person has collected, I imagine that the normal thing is that it appears with the last item you have had or if you have not had any despite having collected some, that nothing appears.

**Comment by Andrey309a** [comment]
It seems that the bug of dropping the item and being able to use it only occurs at the first use of the item, after that it does not occur.

**Comment by Andrey309a** [comment]
It also does not take into account if the item has been used and is in cooldown, if the item has not been picked up by anyone else, but the cooldown has already passed and the item already has the light to use it, when you pick it up you will see that the cooldown is still active and you can not use the item until the cooldown is over.

**Comment by Oz-Lin** [comment]
Linux server?
The "drop weapon" signature needs an update

**Comment by Andrey309a** [comment]
> Linux server? The "drop weapon" signature needs an update

Yes, Linux server

**Comment by Andrey309a** [comment]
> Linux server? The "drop weapon" signature needs an update

Do you have that updated version?

**Comment by Oz-Lin** [comment]
Nope, still have no idea about how to find signatures

**Comment by Andrey309a** [comment]
Also when a player dies and had an item, the item disappears.

**Comment by darkerz7** [comment]
> Also when a player dies and had an item, the item disappears.

weapon cleaner or CVAR mp_death_drop_gun or "ForceDrop": true -> false

**Comment by darkerz7** [comment]
and need find signatures for linux. the drop method in linux is different from the windows method

**Comment by Andrey309a** [comment]
If i use mp_death_drop_gun 0 cant drop my weapon when im alive, lol

**Comment by darkerz7** [comment]
> Nope, still have no idea about how to find signatures

found
"CPlayer_WeaponServices_WeaponDrop": {
        "signatures": {
            "library": "server",
            "windows": "48 89 5C 24 08 48 89 74 24 18 55 57 41 54 41 56 41 57 48 8D 6C 24 C9",
            "linux": "55 48 89 E5 41 57 49 89 F7 41 56 49 89 CE 41 55 41 54"
        }
    }

between #SFUI_Notice_YouDroppedWeapon and #SFUI_Notice_CannotDropWeapon -> sub_CE0E90(a1, v7, 1LL, 0LL);

**Comment by Andrey309a** [comment]
I take this to leave another error, I have tried several times already, but it seems that when there is more than one item of game_ui is broken, the timer of one of them does not work, in this case using only 2, the right click timer of the item that has the 2 functions, left and right stops working when the 2 items are in the cfg (I have left only two to demonstrate, if I put them all do not work).
Video: https://www.dropbox.com/scl/fi/untrhkn1rxmlkqgorv3qz/Counter-strike-2-2024.12.19-21.20.22.07.mp4?rlkey=wzhjfl2hz7lnor3rnp5wuy1i5&st=jkrl7d83&dl=0

Map file used
[ze_tesv_skyrim_p.json](https://github.com/user-attachments/files/18202875/ze_tesv_skyrim_p.json)

**Comment by darkerz7** [comment]
> I take this to leave another error, I have tried several times already, but it seems that when there is more than one item of game_ui is broken, the timer of one of them does not work, in this case using only 2, the right click timer of the item that has the 2 functions, left and right stops working when the 2 items are in the cfg (I have left only two to demonstrate, if I put them all do not work). Video: https://www.dropbox.com/scl/fi/untrhkn1rxmlkqgorv3qz/Counter-strike-2-2024.12.19-21.20.22.07.mp4?rlkey=wzhjfl2hz7lnor3rnp5wuy1i5&st=jkrl7d83&dl=0
> 
> Map file used [ze_tesv_skyrim_p.json](https://github.com/user-attachments/files/18202875/ze_tesv_skyrim_p.json)

maybe the item has a func_physbox, it is automatically detected as a button and interferes, it is necessary to add a puff for the func_physbox. I will take a closer look in the evening. as far as I remember, ze_fapscape has the same problem

**Comment by Andrey309a** [comment]
> > I take this to leave another error, I have tried several times already, but it seems that when there is more than one item of game_ui is broken, the timer of one of them does not work, in this case using only 2, the right click timer of the item that has the 2 functions, left and right stops working when the 2 items are in the cfg (I have left only two to demonstrate, if I put them all do not work). Video: https://www.dropbox.com/scl/fi/untrhkn1rxmlkqgorv3qz/Counter-strike-2-2024.12.19-21.20.22.07.mp4?rlkey=wzhjfl2hz7lnor3rnp5wuy1i5&st=jkrl7d83&dl=0
> > Map file used [ze_tesv_skyrim_p.json](https://github.com/user-attachments/files/18202875/ze_tesv_skyrim_p.json)
> 
> maybe the item has a func_physbox, it is automatically detected as a button and interferes, it is necessary to add a empty struct for the func_physbox. I will take a closer look in the evening. as far as I remember, ze_fapscape has the same problem

correct, there is an item in fapescape that doesn't work the timer either (if I remember correctly), it would be nice to have an example of how to cfg this when you have it, thanks.

**Comment by darkerz7** [comment]
> > > I take this to leave another error, I have tried several times already, but it seems that when there is more than one item of game_ui is broken, the timer of one of them does not work, in this case using only 2, the right click timer of the item that has the 2 functions, left and right stops working when the 2 items are in the cfg (I have left only two to demonstrate, if I put them all do not work). Video: https://www.dropbox.com/scl/fi/untrhkn1rxmlkqgorv3qz/Counter-strike-2-2024.12.19-21.20.22.07.mp4?rlkey=wzhjfl2hz7lnor3rnp5wuy1i5&st=jkrl7d83&dl=0
> > > Map file used [ze_tesv_skyrim_p.json](https://github.com/user-attachments/files/18202875/ze_tesv_skyrim_p.json)
> > 
> > 
> > maybe the item has a func_physbox, it is automatically detected as a button and interferes, it is necessary to add a empty struct for the func_physbox. I will take a closer look in the evening. as far as I remember, ze_fapscape has the same problem
> 
> correct, there is an item in fapescape that doesn't work the timer either (if I remember correctly), it would be nice to have an example of how to cfg this when you have it, thanks.

fixed 0.DZ.10.beta
